#!/bin/bash

SUB_DIRS=(`find . -name \*.nas | sed -e 's|\.\/||' -e 's|\/.*||' | sort -u`)
NAS_DIRS=(`find . -name \*.nas | sed -r 's|/[^/]+$||'| sort -u`)

echo "Please add following statements in CMakeLists.txt"
echo "-------------------------------------------------"

for SUB_DIR in ${SUB_DIRS[@]}
do
    echo "add_subdirectory(${SUB_DIR})"
done
echo ""

echo "-------------------------------------------------"
echo "Debugging...creating subdir's CMakeLists.txt"
echo "-------------------------------------------------"
echo ""

for SUB_DIR in ${SUB_DIRS[@]}
do
    CHILD_DIRS=(`printf -- '%s\n' "${NAS_DIRS[@]}" | grep ${SUB_DIR}`)
    CMAKELISTS="${SUB_DIR}/CMakeLists.txt"

    echo "#----------------------------------------------------------" | tee    ${CMAKELISTS}
    echo "message(STATUS \"Entering directory projects/${SUB_DIR}/\")" | tee -a ${CMAKELISTS}
    for CHILD_DIR in ${CHILD_DIRS[@]}
    do
	CHILD_STR=`echo ${CHILD_DIR} | sed -e 's|\.\/.*\/||' `
	echo "add_subdirectory(${CHILD_STR})" | tee -a ${CMAKELISTS}
    done
    echo ""
done

#do
#
#    FILEPATHS=`find ${FILE_DIR} -name \*.nas`
#    FILENAMES=`find ${FILE_DIR} -name \*.nas -printf "%f "`
#    BIN_NAMES=`echo ${FILENAMES} | sed -e 's/.nas/.img/g'`
#
#    SRCS_TEXT=`echo ${FILENAMES} | sed -e 's/.nas//g'`
#    SRCS_WITHOUT_EXT=($SRCS_TEXT)
#
#    echo -e "#"                                                           > ${FILE_DIR}/Makefile.am
#    echo -e "# Generated by automake.sh "                                >> ${FILE_DIR}/Makefile.am
#    echo -e "#"                                                          >> ${FILE_DIR}/Makefile.am
#    echo -e ""                                                           >> ${FILE_DIR}/Makefile.am
#    echo -e "include \$(top_builddir)/rules.mk"                          >> ${FILE_DIR}/Makefile.am
#    echo -e "NASK = \$(top_builddir)/src/opennask\$(EXEEXT)"             >> ${FILE_DIR}/Makefile.am
#    echo -e "FDSTAT = \$(top_builddir)/fatlib/examples/fdstat\$(EXEEXT)" >> ${FILE_DIR}/Makefile.am
#    echo -e ""                                                           >> ${FILE_DIR}/Makefile.am
#    echo -e "bin_PROGRAMS = ${NASK} ${BIN_NAMES}"                        >> ${FILE_DIR}/Makefile.am
#
#    for (( I = 0; I < ${#SRCS_WITHOUT_EXT[@]}; ++I ))
#    do
# 	echo -e "${SRCS_WITHOUT_EXT[$I]}_img_SOURCES = ${SRCS_WITHOUT_EXT[$I]}.nas" >> ${FILE_DIR}/Makefile.am
#    done
#    #
#    # Create wine task
#    echo -e ""							         >> ${FILE_DIR}/Makefile.am
#    echo -e "wine: all"							 >> ${FILE_DIR}/Makefile.am
#    for (( I = 0; I < ${#SRCS_WITHOUT_EXT[@]}; ++I ))
#    do
# 	echo -e "\t\t\$(WINE_NASK) ${SRCS_WITHOUT_EXT[$I]}.nas ${SRCS_WITHOUT_EXT[$I]}_wine.img" >> ${FILE_DIR}/Makefile.am
# 	echo -e "\t\tod -t x1 ${SRCS_WITHOUT_EXT[$I]}.img	> ${SRCS_WITHOUT_EXT[$I]}_f.txt" >> ${FILE_DIR}/Makefile.am
# 	echo -e "\t\tod -t x1 ${SRCS_WITHOUT_EXT[$I]}_wine.img	> ${SRCS_WITHOUT_EXT[$I]}_t.txt" >> ${FILE_DIR}/Makefile.am
#    done
#    #
#    # Create each targets tasks
#    echo -e ""                                                                           >> ${FILE_DIR}/Makefile.am
#    for (( I = 0; I < ${#SRCS_WITHOUT_EXT[@]}; ++I ))
#    do
# 	echo -e "${SRCS_WITHOUT_EXT[$I]}.img\$(EXEEXT) : ${SRCS_WITHOUT_EXT[$I]}.nas"	 >> ${FILE_DIR}/Makefile.am
# 	echo -e "\t\t\$(NASK) ${SRCS_WITHOUT_EXT[$I]}.nas ${SRCS_WITHOUT_EXT[$I]}.img"	 >> ${FILE_DIR}/Makefile.am
# 	if [ "${SRCS_WITHOUT_EXT[$I]}" = "ipl" ]; then
# 	    echo -e "\t\t\$(FDSTAT) ${SRCS_WITHOUT_EXT[$I]}.img"				 >> ${FILE_DIR}/Makefile.am
# 	fi
# 	echo -e ""                                      				 >> ${FILE_DIR}/Makefile.am
#    done
#
#    AC_CONFIG_FILE=`echo ${FILE_DIR}/Makefile | sed -e 's/^\./projects/g'`
#    echo -e "\t${AC_CONFIG_FILE}"
#done
