/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef __SCANNER_H__
#define __SCANNER_H__ 1

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared.
#ifndef YY_DECL
#define YY_DECL \
    int         \
    NaskScanner::lex(                        \
    nask_::NaskParser::semantic_type* const yylval, \
    nask_::NaskParser::location_type* yylloc        \
    )
#endif

#if !defined(yyFlexLexerOnce)
#   include "FlexLexer.h"
#endif

#include "bison.hh"
#include "location.hh"



class NaskScanner : public yyFlexLexer {
public:

    NaskScanner(std::istream *in);
    virtual ~NaskScanner();

    virtual
    int lex( nask_::NaskParser::semantic_type * const lval,
             nask_::NaskParser::location_type *location );
    // YY_DECL defined in .ll file. Method body created by flex in Lexer.cc

    /* yyval ptr */
    nask_::NaskParser::semantic_type *yylval = nullptr;
    /* location ptr */
    nask_::NaskParser::location_type *loc    = nullptr;
};



#endif /* END __SCANNER_H__ */
