name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest # focal

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Update submodules
      id: update
      run: git submodule update --remote --recursive

    - name: Run git status
      id: status
      run: echo "::set-output name=status::$(git status -s)"

    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: 3.17.2
        ninja: 1.9.0

    - name: Install build tools
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: cpputest libcpputest-dev gcc g++ libc6-dev-i386 linux-headers-generic bison flex libfl-dev
        version: 1.0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja && ninja images

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
