name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest # =focal

    steps:
      - uses: actions/checkout@v2

      - name: Install build tools
        run: sudo apt-get install ninja-build cpputest gcc g++ libc6-dev-i386 linux-headers-generic

      - name: Configure cmake
        run: cmake -B ${{github.workspace}}/build -G Ninja

      - name: Build and Test
        working-directory: ${{github.workspace}}/build
        run: ninja && ninja images && ctest
