name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest # focal

    steps:
    - uses: actions/checkout@v2

    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: 3.17.2
        ninja: 1.9.0

    - name: Install build tools
      run: sudo apt-get install cpputest libcpputest-dev gcc g++ libc6-dev-i386 linux-headers-generic

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja && ninja images

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
