name: CMake

on:
  push:
    branches: ['*']

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest # jammy

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Update submodules
      id: update
      run: git submodule update --remote --recursive

    - name: Run git status
      id: status
      run: echo "::set-output name=status::$(git status -s)"

    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: 3.17.2
        ninja: 1.9.0

    - name: Install build tools
      uses: awalsh128/cache-apt-pkgs-action@v1.1.0
      with:
        packages: gcc g++ libc6-dev-i386 linux-headers-generic bison flex libfl-dev
        version: 1.0

    - name: Configure CMake
      uses: lukka/run-cmake@v10.5
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-G Ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
        buildWithCMake: true
        buildDirectory: '${{ github.workspace }}/build'

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
