name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [issues/*]

jobs:
  build:
    runs-on: ubuntu-latest # =focalb

    steps:
      - name: Install build tools
        run: sudo apt-get install cmake ninja-build cpputest gcc-4.9 g++4.9 libc6-dev-i386 linux-headers-generic
      - name: Configure cmake
        run: mkdir build && cd build && CXX=g++-4.9 CC=gcc-4.9 cmake -G Ninja ..
      - name: Build and Test
        run: ninja && ninja images && ctest
